logo: # add logo name
title: Mary Morgan Keenan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Mary Morgan Keenan # add banner title
banner-desc: Software Engineer, Design Enthusiast, and Sustainability Advocate # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Mary Morgan Keenan # your name
about-author: I graduated from Olin College of Engineering in 2019 with a major in Computing. I'm interested in designing for underserved populations, solving the Grand Challenges, and political activism. My work experience lies primarily in the data analytics space, but I also have experience with user-oriented design and hardware integration. # about author
email: mary.keenan@olin.edu # your email

# Social link
linkedin: https://linkedin.com/in/mary-keenan # add url link

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
remote_theme: Bef